name: Build and publish site
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build page
        run: NODE_ENV=production npx @11ty/eleventy

      - name: Publish to Github Pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: _site
